name: Run Thermostat Script

on:
  schedule:
    - cron: '0 0 31 2 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.10'  # Specify Python 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Check for pkg_resources
        run: |
          python -c "import pkg_resources; print('pkg_resources is available')"

      - name: Run Script
        run: |
          python thermostat.py
        env:
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          SWITCHBOT_SECRET: ${{ secrets.SWITCHBOT_SECRET }}
          ADAFRUIT_IO_USERNAME: ${{ secrets.ADAFRUIT_IO_USERNAME }}
          ADAFRUIT_IO_KEY: ${{ secrets.ADAFRUIT_IO_KEY }}
